### ISSUE TITLE
"Padding size should be less.." error for some WAV files

### ISSUE THREAD

**Issue by agershun** [deepvk/NISQA-s#3]
Another problem for some WAV files

```
/Users/agershun/repo/whisper/NISQA-s/.venv/lib/python3.10/site-packages/torch/nn/modules/rnn.py:82: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=1 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "
NOI    COL   DISC  LOUD  MOS
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/agershun/repo/whisper/NISQA-s/scripts/run_infer_file.py", line 33, in <module>
    out, h0, c0 = process(audio, sr, model, h0, c0, args)
  File "/Users/agershun/repo/whisper/NISQA-s/src/utils/process_utils.py", line 79, in process
    audio = get_ta_melspec(
  File "/Users/agershun/repo/whisper/NISQA-s/src/utils/process_utils.py", line 39, in get_ta_melspec
    S = melSpec(y)
  File "/Users/agershun/repo/whisper/NISQA-s/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/agershun/repo/whisper/NISQA-s/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/agershun/repo/whisper/NISQA-s/.venv/lib/python3.10/site-packages/torchaudio/transforms/_transforms.py", line 619, in forward
    specgram = self.spectrogram(waveform)
  File "/Users/agershun/repo/whisper/NISQA-s/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/agershun/repo/whisper/NISQA-s/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/agershun/repo/whisper/NISQA-s/.venv/lib/python3.10/site-packages/torchaudio/transforms/_transforms.py", line 110, in forward
    return F.spectrogram(
  File "/Users/agershun/repo/whisper/NISQA-s/.venv/lib/python3.10/site-packages/torchaudio/functional/functional.py", line 126, in spectrogram
    spec_f = torch.stft(
  File "/Users/agershun/repo/whisper/NISQA-s/.venv/lib/python3.10/site-packages/torch/functional.py", line 648, in stft
    input = F.pad(input.view(extended_shape), [pad, pad], pad_mode)
RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (480, 480) at dimension 2 of input [1, 88200, 2]
```

This is a sample of the file with the problem:
https://drive.google.com/file/d/1CHZ4TZaILu-K5rsA8XkPAEDbt_2VGXVd/view?usp=sharing

**Comment by JBloodless** [comment]
Files for inference should be mono; this problem occurs only on stereo files
